---
title: "R Notebook"
output: html_notebook
---

```{r}
require(pacman)
p_load(adabag, plyr,doParallel,randomForest)
```

#Configura multiThreding
```{r}

cl <- makeCluster(detectCores()-2)
registerDoParallel(cl)
```

#configura entrada
```{r}
santander <- read.csv("./train.csv")
santander$TARGET <- as.factor(santander$TARGET) 
 plot(santander$TARGET)
s <- sample(76020,15000) 
x_santander_train <- santander[s,]

```

#Procura as melhores variáveis indenpendentes para classificar
```{r}
modelo1500 <- randomForest(TARGET~.,               
                           data=x_santander_train,
                           ntree=1500,
                           importance=TRUE)

modelo_var_xgbLinear  <- train(TARGET~.,
                      data=santander[s,],
                      method="xgbLinear",
                      trControl=control)

```
#Plota na tela e sekeciona principais
```{r}
varImpPlot(modelo1500,type=2)


col <- c("var15", "var38","saldo_var30","saldo_var42", "saldo_medio_var5_ult3", "saldo_medio_var5_ult1", 
         "saldo_medio_var5_hace2", "num_var45_ult3", "saldo_var5", "saldo_medio_var5_hace3", "num_var45_hace2",
         "num_var22_ult3", "num_var45_hace3","num_var45_ult1","num_meses_var5_ult3","num_op_var41_efect_ult3","TARGET")


x_santander_train <- x_santander_train[,col]

```

#preparando parametros
```{r}
control <- trainControl(method="repeatedcv", number=8, repeats=3)
metric <- "Accuracy"
set.seed(7)
mtry <- sqrt(ncol(x_santander_train))
tunegrid <- expand.grid(.mtry=mtry)
```

#Svm com kernel linear
```{r}
modelo_svmLinear <- train(TARGET~.,
                         data=x_santander_train,
                         method="svmLinear",
                         trControl=control)
print(modelo_svmLinear)
```

#RandomFlorest
```{r}


modeloRF <- train(TARGET~.,
                    data=x_santander_train,
                    method="rf",
                    metric=metric,
                    tuneGrid=tunegrid,
                    trControl=control)
print(modeloRF)

```

#SVM com kernel polinomial
```{r}
 modelo_svmPoly <- train(TARGET~.,
                         data=x_santander_train,
                         method="svmPoly",
                         trControl=control)
 modelo_svmPoly
```

```{r}
modelo_xgbDART <- train(TARGET~.,
                    data=x_santander_train,
                    method="xgbDART",
                    metric=metric,
                    tuneGrid=tunegrid,
                    trControl=control)
print(modelo_xgbDART)
```
#Os sistemas baseados em regras difusas

